/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package demo.customermanagement.core.dto.kafkaresponse;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class individualIdentification_record extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5286974863002052060L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"individualIdentification_record\",\"namespace\":\"demo.customermanagement.core.dto.kafkaresponse\",\"fields\":[{\"name\":\"identificationId\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"identificationType\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"issuingDate\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"issuingAuthority\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"placeOfIssue\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"validFor\",\"type\":{\"type\":\"record\",\"name\":\"validFor_record\",\"fields\":[{\"name\":\"startDateTime\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"endDateTime\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<individualIdentification_record> ENCODER =
      new BinaryMessageEncoder<individualIdentification_record>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<individualIdentification_record> DECODER =
      new BinaryMessageDecoder<individualIdentification_record>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<individualIdentification_record> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<individualIdentification_record> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<individualIdentification_record>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this individualIdentification_record to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a individualIdentification_record from a ByteBuffer. */
  public static individualIdentification_record fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.String identificationId;
   private java.lang.String identificationType;
   private java.lang.String issuingDate;
   private java.lang.String issuingAuthority;
   private java.lang.String placeOfIssue;
   private validFor_record validFor;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public individualIdentification_record() {}

  /**
   * All-args constructor.
   * @param identificationId The new value for identificationId
   * @param identificationType The new value for identificationType
   * @param issuingDate The new value for issuingDate
   * @param issuingAuthority The new value for issuingAuthority
   * @param placeOfIssue The new value for placeOfIssue
   * @param validFor The new value for validFor
   */
  public individualIdentification_record(java.lang.String identificationId, java.lang.String identificationType, java.lang.String issuingDate, java.lang.String issuingAuthority, java.lang.String placeOfIssue, validFor_record validFor) {
    this.identificationId = identificationId;
    this.identificationType = identificationType;
    this.issuingDate = issuingDate;
    this.issuingAuthority = issuingAuthority;
    this.placeOfIssue = placeOfIssue;
    this.validFor = validFor;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return identificationId;
    case 1: return identificationType;
    case 2: return issuingDate;
    case 3: return issuingAuthority;
    case 4: return placeOfIssue;
    case 5: return validFor;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: identificationId = (java.lang.String)value$; break;
    case 1: identificationType = (java.lang.String)value$; break;
    case 2: issuingDate = (java.lang.String)value$; break;
    case 3: issuingAuthority = (java.lang.String)value$; break;
    case 4: placeOfIssue = (java.lang.String)value$; break;
    case 5: validFor = (validFor_record)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'identificationId' field.
   * @return The value of the 'identificationId' field.
   */
  public java.lang.String getIdentificationId() {
    return identificationId;
  }


  /**
   * Gets the value of the 'identificationType' field.
   * @return The value of the 'identificationType' field.
   */
  public java.lang.String getIdentificationType() {
    return identificationType;
  }


  /**
   * Gets the value of the 'issuingDate' field.
   * @return The value of the 'issuingDate' field.
   */
  public java.lang.String getIssuingDate() {
    return issuingDate;
  }


  /**
   * Gets the value of the 'issuingAuthority' field.
   * @return The value of the 'issuingAuthority' field.
   */
  public java.lang.String getIssuingAuthority() {
    return issuingAuthority;
  }


  /**
   * Gets the value of the 'placeOfIssue' field.
   * @return The value of the 'placeOfIssue' field.
   */
  public java.lang.String getPlaceOfIssue() {
    return placeOfIssue;
  }


  /**
   * Gets the value of the 'validFor' field.
   * @return The value of the 'validFor' field.
   */
  public validFor_record getValidFor() {
    return validFor;
  }


  /**
   * Creates a new individualIdentification_record RecordBuilder.
   * @return A new individualIdentification_record RecordBuilder
   */
  public static Builder newBuilder() {
    return new Builder();
  }

  /**
   * Creates a new individualIdentification_record RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new individualIdentification_record RecordBuilder
   */
  public static Builder newBuilder(Builder other) {
    return new Builder(other);
  }

  /**
   * Creates a new individualIdentification_record RecordBuilder by copying an existing individualIdentification_record instance.
   * @param other The existing instance to copy.
   * @return A new individualIdentification_record RecordBuilder
   */
  public static Builder newBuilder(individualIdentification_record other) {
    return new Builder(other);
  }

  /**
   * RecordBuilder for individualIdentification_record instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<individualIdentification_record>
    implements org.apache.avro.data.RecordBuilder<individualIdentification_record> {

    private java.lang.String identificationId;
    private java.lang.String identificationType;
    private java.lang.String issuingDate;
    private java.lang.String issuingAuthority;
    private java.lang.String placeOfIssue;
    private validFor_record validFor;
    private validFor_record.Builder validForBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.identificationId)) {
        this.identificationId = data().deepCopy(fields()[0].schema(), other.identificationId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.identificationType)) {
        this.identificationType = data().deepCopy(fields()[1].schema(), other.identificationType);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.issuingDate)) {
        this.issuingDate = data().deepCopy(fields()[2].schema(), other.issuingDate);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.issuingAuthority)) {
        this.issuingAuthority = data().deepCopy(fields()[3].schema(), other.issuingAuthority);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.placeOfIssue)) {
        this.placeOfIssue = data().deepCopy(fields()[4].schema(), other.placeOfIssue);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.validFor)) {
        this.validFor = data().deepCopy(fields()[5].schema(), other.validFor);
        fieldSetFlags()[5] = true;
      }
      if (other.hasValidForBuilder()) {
        this.validForBuilder = validFor_record.newBuilder(other.getValidForBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing individualIdentification_record instance
     * @param other The existing instance to copy.
     */
    private Builder(individualIdentification_record other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.identificationId)) {
        this.identificationId = data().deepCopy(fields()[0].schema(), other.identificationId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.identificationType)) {
        this.identificationType = data().deepCopy(fields()[1].schema(), other.identificationType);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.issuingDate)) {
        this.issuingDate = data().deepCopy(fields()[2].schema(), other.issuingDate);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.issuingAuthority)) {
        this.issuingAuthority = data().deepCopy(fields()[3].schema(), other.issuingAuthority);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.placeOfIssue)) {
        this.placeOfIssue = data().deepCopy(fields()[4].schema(), other.placeOfIssue);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.validFor)) {
        this.validFor = data().deepCopy(fields()[5].schema(), other.validFor);
        fieldSetFlags()[5] = true;
      }
      this.validForBuilder = null;
    }

    /**
      * Gets the value of the 'identificationId' field.
      * @return The value.
      */
    public java.lang.String getIdentificationId() {
      return identificationId;
    }

    /**
      * Sets the value of the 'identificationId' field.
      * @param value The value of 'identificationId'.
      * @return This builder.
      */
    public Builder setIdentificationId(java.lang.String value) {
      validate(fields()[0], value);
      this.identificationId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'identificationId' field has been set.
      * @return True if the 'identificationId' field has been set, false otherwise.
      */
    public boolean hasIdentificationId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'identificationId' field.
      * @return This builder.
      */
    public Builder clearIdentificationId() {
      identificationId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'identificationType' field.
      * @return The value.
      */
    public java.lang.String getIdentificationType() {
      return identificationType;
    }

    /**
      * Sets the value of the 'identificationType' field.
      * @param value The value of 'identificationType'.
      * @return This builder.
      */
    public Builder setIdentificationType(java.lang.String value) {
      validate(fields()[1], value);
      this.identificationType = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'identificationType' field has been set.
      * @return True if the 'identificationType' field has been set, false otherwise.
      */
    public boolean hasIdentificationType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'identificationType' field.
      * @return This builder.
      */
    public Builder clearIdentificationType() {
      identificationType = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'issuingDate' field.
      * @return The value.
      */
    public java.lang.String getIssuingDate() {
      return issuingDate;
    }

    /**
      * Sets the value of the 'issuingDate' field.
      * @param value The value of 'issuingDate'.
      * @return This builder.
      */
    public Builder setIssuingDate(java.lang.String value) {
      validate(fields()[2], value);
      this.issuingDate = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'issuingDate' field has been set.
      * @return True if the 'issuingDate' field has been set, false otherwise.
      */
    public boolean hasIssuingDate() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'issuingDate' field.
      * @return This builder.
      */
    public Builder clearIssuingDate() {
      issuingDate = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'issuingAuthority' field.
      * @return The value.
      */
    public java.lang.String getIssuingAuthority() {
      return issuingAuthority;
    }

    /**
      * Sets the value of the 'issuingAuthority' field.
      * @param value The value of 'issuingAuthority'.
      * @return This builder.
      */
    public Builder setIssuingAuthority(java.lang.String value) {
      validate(fields()[3], value);
      this.issuingAuthority = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'issuingAuthority' field has been set.
      * @return True if the 'issuingAuthority' field has been set, false otherwise.
      */
    public boolean hasIssuingAuthority() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'issuingAuthority' field.
      * @return This builder.
      */
    public Builder clearIssuingAuthority() {
      issuingAuthority = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'placeOfIssue' field.
      * @return The value.
      */
    public java.lang.String getPlaceOfIssue() {
      return placeOfIssue;
    }

    /**
      * Sets the value of the 'placeOfIssue' field.
      * @param value The value of 'placeOfIssue'.
      * @return This builder.
      */
    public Builder setPlaceOfIssue(java.lang.String value) {
      validate(fields()[4], value);
      this.placeOfIssue = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'placeOfIssue' field has been set.
      * @return True if the 'placeOfIssue' field has been set, false otherwise.
      */
    public boolean hasPlaceOfIssue() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'placeOfIssue' field.
      * @return This builder.
      */
    public Builder clearPlaceOfIssue() {
      placeOfIssue = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'validFor' field.
      * @return The value.
      */
    public validFor_record getValidFor() {
      return validFor;
    }

    /**
      * Sets the value of the 'validFor' field.
      * @param value The value of 'validFor'.
      * @return This builder.
      */
    public Builder setValidFor(validFor_record value) {
      validate(fields()[5], value);
      this.validForBuilder = null;
      this.validFor = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'validFor' field has been set.
      * @return True if the 'validFor' field has been set, false otherwise.
      */
    public boolean hasValidFor() {
      return fieldSetFlags()[5];
    }

    /**
     * Gets the Builder instance for the 'validFor' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public validFor_record.Builder getValidForBuilder() {
      if (validForBuilder == null) {
        if (hasValidFor()) {
          setValidForBuilder(validFor_record.newBuilder(validFor));
        } else {
          setValidForBuilder(validFor_record.newBuilder());
        }
      }
      return validForBuilder;
    }

    /**
     * Sets the Builder instance for the 'validFor' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public Builder setValidForBuilder(validFor_record.Builder value) {
      clearValidFor();
      validForBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'validFor' field has an active Builder instance
     * @return True if the 'validFor' field has an active Builder instance
     */
    public boolean hasValidForBuilder() {
      return validForBuilder != null;
    }

    /**
      * Clears the value of the 'validFor' field.
      * @return This builder.
      */
    public Builder clearValidFor() {
      validFor = null;
      validForBuilder = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public individualIdentification_record build() {
      try {
        individualIdentification_record record = new individualIdentification_record();
        record.identificationId = fieldSetFlags()[0] ? this.identificationId : (java.lang.String) defaultValue(fields()[0]);
        record.identificationType = fieldSetFlags()[1] ? this.identificationType : (java.lang.String) defaultValue(fields()[1]);
        record.issuingDate = fieldSetFlags()[2] ? this.issuingDate : (java.lang.String) defaultValue(fields()[2]);
        record.issuingAuthority = fieldSetFlags()[3] ? this.issuingAuthority : (java.lang.String) defaultValue(fields()[3]);
        record.placeOfIssue = fieldSetFlags()[4] ? this.placeOfIssue : (java.lang.String) defaultValue(fields()[4]);
        if (validForBuilder != null) {
          record.validFor = this.validForBuilder.build();
        } else {
          record.validFor = fieldSetFlags()[5] ? this.validFor : (validFor_record) defaultValue(fields()[5]);
        }
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<individualIdentification_record>
    WRITER$ = (org.apache.avro.io.DatumWriter<individualIdentification_record>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<individualIdentification_record>
    READER$ = (org.apache.avro.io.DatumReader<individualIdentification_record>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
