server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:additional_data
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

enable:
  ms-authorization:
    filter: true